### ISSUE TITLE
关于数据集文件损坏的问题

### ISSUE THREAD

**Issue by czy19** [marlin-codes/HTGN#2]
你好，我在该项目的谷歌硬盘中下载了数据集，其中facebook的数据文件(fbw.data)损坏了，代码无法运行。
请问能再上传一次该文件吗？

**Comment by marlin-codes** [comment]
Thanks for your comment. Please download the updated data at https://drive.google.com/file/d/1qv98H-mI2BtdNGexlTIm127xslHslxS1/view?usp=sharing
